tree folder visualization
oenzoferrari/missopad pull request #5
Opened 2022-04-22 22:31 UTC by RiccardoCafa

This is a feature that shows the hierarchy for the current folder, I've named it "missogates" and used an airplane cause is like going somewhere and using a specific gate to reach the destination.

To use is very simple, just click on the airplane then should appear a hyperlink for every children's folder for the current one. If none then a message should appear telling you there are no gates. Click it again to make it disappear.

2022-04-22 23:21 UTC, oenzoferrari requested changes
Very cool, I suggested some minor style improvements 👍

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Pad.tsx
> +      {missogates ? <Tree /> : <></>}
```suggestion
      {missogates && <Tree />}
```

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Pad.tsx
> +  const [missogates, setMissogates] = useState<boolean>(false);
```suggestion
  const [showMissogates, setShowMissogates] = useState<boolean>(false);
```

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Pad.tsx
> +          ✈️{missogates ? " missogates" : ""}
```suggestion
          onClick={() => setShowMissogates(!showmMissogates)}
        >
          ✈️{showMissogates && " missogates"}
```

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Pad.tsx
> +      {missogates ? <Tree /> : <></>}
P.s.: not sure if this works

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Tree.tsx
> +  }
```suggestion
    const children: DataSnapshot[] = [];
    node.forEach((child) => {
      if (child.size > 0) {
        childs.push(child);
      }
    });
    return children;
  }
```

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Tree.tsx
> +    });
```suggestion
    return routes.filter(route => route.size > 0).map((route) => {
        return (
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              whiteSpace: "nowrap",
            }}
          >
            {mountTree(route)}
          </div>
        );
    });
```

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Tree.tsx
> +        {(level === 1 ? ".\\" : "↳ ") + route.key}
I think these should be constants, something like:

```js
ROOT_SYMBOL = ".\\"
CHILD_SYMBOL = "↳ "
```

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Tree.tsx
> +  }
```suggestion
    const children: DataSnapshot[] = getDataSnapshotArray(node);

    return (
      <>
        {getRouteLink(node, subpath, recursion++)}
        {children.map((route) => {
          return mountTree(route, subpath + "/" + node.key, recursion);
        })}
      </>
    );
  }
```

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Tree.tsx
> +      {routes.length == 0 ? <p>no gates here :(</p> : <></>}
```suggestion
      {routes.length == 0 && <p>no gates here :(</p>}
```

P.s.: Not sure if this works

2022-04-22 23:21 UTC, oenzoferrari commented on src/components/Pad.tsx
> +          ✈️{missogates ? " missogates" : ""}
P.s.: not sure if this works

2022-04-22 23:57 UTC, RiccardoCafa commented on src/components/Tree.tsx
> +    });
It doesn't work without returning JSX

2022-04-23 00:11 UTC, oenzoferrari approved these changes

2022-04-23 00:12 UTC, merged